// This file is generated by scripts/generate-masm.mjs from the MASM contract sources.
// Do not edit it by hand.

export const MULTISIG_ACCOUNT_COMPONENT_MASM = `# Multi-Signature RPO Falcon 512 Authentication Component

use openzeppelin::auth::multisig

type BeWord = struct @bigendian { a: felt, b: felt, c: felt, d: felt }

pub use multisig::update_signers_and_threshold
pub use multisig::update_procedure_threshold

pub proc auth_tx_multisig(salt: BeWord)
    exec.multisig::auth_tx
    exec.multisig::assert_new_tx
end
`;

export const MULTISIG_PSM_ACCOUNT_COMPONENT_MASM = `# Multi-Signature RPO Falcon 512 Authentication Component With PSM

use openzeppelin::auth::multisig
use openzeppelin::auth::psm

type BeWord = struct @bigendian { a: felt, b: felt, c: felt, d: felt }

pub use multisig::update_signers_and_threshold
pub use multisig::update_procedure_threshold
pub use psm::update_psm_public_key
pub use psm::verify_psm_signature

pub proc auth_tx_multisig_psm(salt: BeWord)
    exec.multisig::auth_tx
    exec.psm::verify_psm_signature
    exec.multisig::assert_new_tx
end
`;

export const MULTISIG_ECDSA_ACCOUNT_COMPONENT_MASM = `# Multi-Signature ECDSA secp256k1 Authentication Component

use openzeppelin::auth::multisig_ecdsa

type BeWord = struct @bigendian { a: felt, b: felt, c: felt, d: felt }

pub use multisig_ecdsa::update_signers_and_threshold
pub use multisig_ecdsa::update_procedure_threshold

pub proc auth_tx_multisig_ecdsa(salt: BeWord)
    exec.multisig_ecdsa::auth_tx
    exec.multisig_ecdsa::assert_new_tx
end
`;

export const MULTISIG_PSM_ECDSA_ACCOUNT_COMPONENT_MASM = `# Multi-Signature ECDSA secp256k1 Authentication Component With PSM

use openzeppelin::auth::multisig_ecdsa
use openzeppelin::auth::psm_ecdsa

type BeWord = struct @bigendian { a: felt, b: felt, c: felt, d: felt }

pub use multisig_ecdsa::update_signers_and_threshold
pub use multisig_ecdsa::update_procedure_threshold
pub use psm_ecdsa::update_psm_public_key
pub use psm_ecdsa::verify_psm_signature

pub proc auth_tx_multisig_psm_ecdsa(salt: BeWord)
    exec.multisig_ecdsa::auth_tx
    exec.psm_ecdsa::verify_psm_signature
    exec.multisig_ecdsa::assert_new_tx
end
`;
