import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, '..');
const repoRoot = path.resolve(packageRoot, '../..');
const packageMasmDir = path.join(packageRoot, 'masm');
const canonicalMasmDir = path.join(repoRoot, 'crates', 'contracts', 'masm', 'auth');
const generatedFilePath = path.join(packageRoot, 'src', 'account', 'masm.ts');
const masmFiles = ['multisig.masm', 'psm.masm'];

function fileExists(dir, fileName) {
  return existsSync(path.join(dir, fileName));
}

function resolveSourceDir() {
  const canonicalAvailable = masmFiles.every((fileName) => fileExists(canonicalMasmDir, fileName));
  if (canonicalAvailable) {
    return canonicalMasmDir;
  }

  const packagedAvailable = masmFiles.every((fileName) => fileExists(packageMasmDir, fileName));
  if (packagedAvailable) {
    return packageMasmDir;
  }

  throw new Error(
    `unable to locate MASM sources in either '${canonicalMasmDir}' or '${packageMasmDir}'`,
  );
}

function writeIfChanged(filePath, contents) {
  if (existsSync(filePath) && readFileSync(filePath, 'utf8') === contents) {
    return;
  }

  writeFileSync(filePath, contents, 'utf8');
}

function toTemplateLiteral(contents) {
  return `\`${contents
    .replaceAll('\\', '\\\\')
    .replaceAll('`', '\\`')
    .replaceAll('${', '\\${')}\``;
}

const sourceDir = resolveSourceDir();
const [multisigSource, psmSource] = masmFiles.map((fileName) =>
  readFileSync(path.join(sourceDir, fileName), 'utf8'),
);

mkdirSync(packageMasmDir, { recursive: true });
writeIfChanged(path.join(packageMasmDir, 'multisig.masm'), multisigSource);
writeIfChanged(path.join(packageMasmDir, 'psm.masm'), psmSource);

const generatedSource = `// This file is generated by scripts/generate-masm.mjs from the MASM contract sources.
// Do not edit it by hand.

export const MULTISIG_MASM = ${toTemplateLiteral(multisigSource)};

export const PSM_MASM = ${toTemplateLiteral(psmSource)};
`;

writeIfChanged(generatedFilePath, generatedSource);
