import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, '..');
const repoRoot = path.resolve(packageRoot, '../..');
const packageMasmDir = path.join(packageRoot, 'masm');
const canonicalMasmDir = path.join(repoRoot, 'crates', 'contracts', 'masm', 'auth');
const generatedFilePath = path.join(packageRoot, 'src', 'account', 'masm.ts');
const masmFiles = [
  ['multisig.masm', 'MULTISIG_MASM'],
  ['multisig_ecdsa.masm', 'MULTISIG_ECDSA_MASM'],
  ['psm.masm', 'PSM_MASM'],
  ['psm_ecdsa.masm', 'PSM_ECDSA_MASM'],
];

function fileExists(dir, fileName) {
  return existsSync(path.join(dir, fileName));
}

function resolveSourceDir() {
  const canonicalAvailable = masmFiles.every(([fileName]) => fileExists(canonicalMasmDir, fileName));
  if (canonicalAvailable) {
    return canonicalMasmDir;
  }

  const packagedAvailable = masmFiles.every(([fileName]) => fileExists(packageMasmDir, fileName));
  if (packagedAvailable) {
    return packageMasmDir;
  }

  throw new Error(
    `unable to locate MASM sources in either '${canonicalMasmDir}' or '${packageMasmDir}'`,
  );
}

function writeIfChanged(filePath, contents) {
  if (existsSync(filePath) && readFileSync(filePath, 'utf8') === contents) {
    return;
  }

  writeFileSync(filePath, contents, 'utf8');
}

function toTemplateLiteral(contents) {
  return `\`${contents
    .replaceAll('\\', '\\\\')
    .replaceAll('`', '\\`')
    .replaceAll('${', '\\${')}\``;
}

const sourceDir = resolveSourceDir();
const masmSources = masmFiles.map(([fileName, exportName]) => ({
  fileName,
  exportName,
  source: readFileSync(path.join(sourceDir, fileName), 'utf8'),
}));

for (const { fileName, source } of masmSources) {
  mkdirSync(packageMasmDir, { recursive: true });
  writeIfChanged(path.join(packageMasmDir, fileName), source);
}

const exportsSource = masmSources.map(({ exportName, source }) =>
  `export const ${exportName} = ${toTemplateLiteral(source)};`,
);

const generatedSource = `// This file is generated by scripts/generate-masm.mjs from the MASM contract sources.
// Do not edit it by hand.

${exportsSource.join('\n\n')}
`;

writeIfChanged(generatedFilePath, generatedSource);
